begin;

create extension if not exists pgtap with schema extensions;
select extensions.plan(36);

insert into auth.users(id,aud,role,email,created_at,updated_at)
values
  ('99000000-0000-4000-8000-000000000001','authenticated','authenticated','blog-staff@example.test',now(),now()),
  ('99000000-0000-4000-8000-000000000002','authenticated','authenticated','blog-admin@example.test',now(),now()),
  ('99000000-0000-4000-8000-000000000003','authenticated','authenticated','blog-inactive@example.test',now(),now());

insert into public.profiles(id,email,display_name,role,is_active)
values
  ('99000000-0000-4000-8000-000000000001','blog-staff@example.test','Blog Staff','staff',true),
  ('99000000-0000-4000-8000-000000000002','blog-admin@example.test','Blog Admin','admin',true),
  ('99000000-0000-4000-8000-000000000003','blog-inactive@example.test','Blog Inactive','staff',false);

select extensions.has_function('public','create_blog_post',array['text','text','text','integer','text','text','text','text[]','text','text'],'create blog RPC exists');
select extensions.has_function('public','update_blog_post',array['uuid','integer','text','text','text','integer','text','text','text','text[]','text','text'],'update blog RPC exists');
select extensions.has_function('public','submit_blog_post_for_review',array['uuid','integer'],'submit blog RPC exists');
select extensions.has_function('public','moderate_blog_post',array['uuid','integer','blog_status','text'],'moderate blog RPC exists');
select extensions.has_function('public','set_blog_post_featured',array['uuid','integer','boolean'],'feature blog RPC exists');
select extensions.has_function('public','archive_blog_post',array['uuid','integer'],'archive blog RPC exists');
select extensions.has_function('public','restore_blog_post',array['uuid','integer'],'restore blog RPC exists');
select extensions.has_table('public','blog_post_revisions','blog revision table exists');
select extensions.has_function('public','restore_blog_post_revision',array['uuid','bigint','integer'],'restore revision RPC exists');

set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000001',true);

select extensions.throws_ok(
  $$ insert into public.blog_posts(slug,title) values('unsafe-direct-blog','Unsafe') $$,
  '42501',null,'direct blog inserts are blocked'
);

create temporary table staff_blog as
select public.create_blog_post(
  'Peraturan Baru untuk Pelaku Usaha',
  'Ringkasan berita bisnis yang cukup panjang.',
  '<p>Isi artikel yang lengkap untuk pengujian editorial.</p>',
  2,'https://example.test/blog-cover.jpg','Business regulation meeting','News',array['business','update'],null,null
) as id;

select extensions.is((select status::text from public.blog_posts where id=(select id from staff_blog)),'draft','new posts start as drafts');
select extensions.is((select created_by from public.blog_posts where id=(select id from staff_blog)),'99000000-0000-4000-8000-000000000001'::uuid,'creator is derived from auth uid');
select extensions.is((select author_name from public.blog_posts where id=(select id from staff_blog)),'Blog Staff','author snapshot is derived from profile');
select extensions.is((select slug from public.blog_posts where id=(select id from staff_blog)),'peraturan-baru-untuk-pelaku-usaha','slug is generated by the database');
select extensions.is((select tags from public.blog_posts where id=(select id from staff_blog)),array['business','update']::text[],'tags are normalized');

select extensions.lives_ok(
  $$ select public.update_blog_post((select id from staff_blog),1,'Peraturan Baru untuk Pelaku Usaha','Ringkasan berita bisnis yang telah diperbarui.','<p>Isi artikel lengkap yang sudah diperbarui oleh staff.</p>',3,'https://example.test/blog-cover.jpg','Business regulation meeting','Legal Update',array['legal'],null,null) $$,
  'creator can edit their draft'
);
select extensions.is((select version from public.blog_posts where id=(select id from staff_blog)),2,'editing advances optimistic version');

select extensions.throws_ok(
  $$ select public.update_blog_post((select id from staff_blog),1,'Peraturan Baru untuk Pelaku Usaha','Ringkasan berita bisnis yang telah diperbarui.','<p>Isi artikel lengkap yang sudah diperbarui oleh staff.</p>',3,'https://example.test/blog-cover.jpg','Business regulation meeting','Legal Update',array['legal'],null,null) $$,
  '40001','blog_post_stale','stale updates are rejected'
);

select extensions.lives_ok(
  $$ select public.submit_blog_post_for_review((select id from staff_blog),2) $$,
  'creator can submit a draft for review'
);
select extensions.is((select status::text from public.blog_posts where id=(select id from staff_blog)),'pending','submitted posts become pending');
select extensions.throws_ok(
  $$ select public.update_blog_post((select id from staff_blog),3,'Peraturan Baru untuk Pelaku Usaha','Ringkasan berita bisnis yang telah diperbarui.','<p>Isi artikel lengkap yang sudah diperbarui oleh staff.</p>',3,'https://example.test/blog-cover.jpg','Business regulation meeting','Legal Update',array['legal'],null,null) $$,
  '42501','blog_edit_forbidden','staff cannot edit a pending post'
);
select extensions.throws_ok(
  $$ select public.moderate_blog_post((select id from staff_blog),3,'published',null) $$,
  '42501','blog_moderation_forbidden','staff cannot publish posts'
);
select extensions.throws_ok(
  $$ select public.archive_blog_post((select id from staff_blog),3) $$,
  '42501','blog_archive_forbidden','staff cannot archive posts'
);

select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000002',true);
select extensions.lives_ok(
  $$ select public.moderate_blog_post((select id from staff_blog),3,'published',null) $$,
  'admin can publish a pending post'
);
select extensions.is((select status::text from public.blog_posts where id=(select id from staff_blog)),'published','published state is stored');
select extensions.isnt((select published_by from public.blog_posts where id=(select id from staff_blog)),null::uuid,'publisher is recorded');
select extensions.lives_ok(
  $$ select public.set_blog_post_featured((select id from staff_blog),4,true) $$,
  'admin can feature a published post'
);
select extensions.ok((select is_featured from public.blog_posts where id=(select id from staff_blog)),'featured state is stored');

select extensions.lives_ok(
  $$ select public.archive_blog_post((select id from staff_blog),5) $$,
  'admin can soft archive a post'
);
select extensions.ok((select archived_at is not null and status='draft'::public.blog_status and not is_featured from public.blog_posts where id=(select id from staff_blog)),'archive hides publication state without deleting history');
select extensions.lives_ok(
  $$ select public.restore_blog_post((select id from staff_blog),6) $$,
  'admin can restore an archived post'
);
select extensions.ok((select archived_at is null and status='draft'::public.blog_status from public.blog_posts where id=(select id from staff_blog)),'restored posts return as drafts');
select extensions.ok((select count(*) >= 7 from public.blog_post_revisions where post_id=(select id from staff_blog)),'every version is retained as an immutable revision');
select extensions.lives_ok(
  $$ select public.restore_blog_post_revision((select id from staff_blog),(select id from public.blog_post_revisions where post_id=(select id from staff_blog) and source_version=2),7) $$,
  'admin can restore an earlier revision'
);
select extensions.ok((select status='draft'::public.blog_status and version=8 and content_md like '%diperbarui%' from public.blog_posts where id=(select id from staff_blog)),'restoring creates a new draft version with historical content');

select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000003',true);
select extensions.throws_ok(
  $$ select public.create_blog_post('Blocked Article','Ringkasan artikel yang cukup panjang.','<p>Isi artikel yang lengkap untuk pengujian akses.</p>',1,null,null,'News','{}'::text[],null,null) $$,
  '42501','blog_staff_access_required','inactive staff cannot create posts'
);

reset role;
select extensions.finish();
rollback;
